version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb/data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  minio:
    command: "server /data --console-address \":9001\""
    image: "minio/minio:latest"
    container_name: minio
    # environment:
    #   MINIO_ROOT_USER: minioadmin
    #   MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./docker/minio/data:/data"
  nginx:
    image: "nginx:latest"
    container_name: nginx
    ports: 
      - "5000:5000"
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./app/frontend/build:/reviewers-like-you:ro"
    depends_on:
      - recommendation1
      - recommendation2
    links:
      - "recommendation1"
      - "recommendation2"
  scraper:
    container_name: scraper
    environment:
      AWS_ACCESS_KEY_ID: fakeKeyId
      AWS_SECRET_ACCESS_KEY: fakeAccessKey
      AWS_DEFAULT_REGION: us-west-2
    depends_on:
      - dynamodb-local
    links:
      - "dynamodb-local"
    build: config/scraper
    volumes:
      - .:/reviewers-like-you
    ports:
      - "5001:5000"
  ingestion:
    container_name: ingestion
    environment:
      AWS_ACCESS_KEY_ID: fakeKeyId
      AWS_SECRET_ACCESS_KEY: fakeAccessKey
      AWS_DEFAULT_REGION: us-west-2
    depends_on:
      - dynamodb-local
    links:
      - "dynamodb-local"
    build: config/ingestion
    volumes:
      - .:/reviewers-like-you
    ports:
      - "5002:5000"
  projection:
    container_name: projection
    environment:
      AWS_ACCESS_KEY_ID: fakeKeyId
      AWS_SECRET_ACCESS_KEY: fakeAccessKey
      AWS_DEFAULT_REGION: us-west-2
    depends_on:
      - dynamodb-local
      - minio
    links:
      - "dynamodb-local"
      - "minio"
    build: config/projection
    volumes:
      - .:/reviewers-like-you
    ports:
      - "5003:5000" 
  recommendation1:
    container_name: recommendation1
    environment:
      AWS_ACCESS_KEY_ID: fakeKeyId
      AWS_SECRET_ACCESS_KEY: fakeAccessKey
      AWS_DEFAULT_REGION: us-west-2
    depends_on:
      - dynamodb-local
      - minio
    links:
      - "dynamodb-local"
      - "minio"
    build: config/recommendation
    volumes:
      - .:/reviewers-like-you
  recommendation2:
    container_name: recommendation2
    environment:
      AWS_ACCESS_KEY_ID: fakeKeyId
      AWS_SECRET_ACCESS_KEY: fakeAccessKey
      AWS_DEFAULT_REGION: us-west-2
    depends_on:
      - dynamodb-local
      - minio
    links:
      - "dynamodb-local"
      - "minio"
    build: config/recommendation
    volumes:
      - .:/reviewers-like-you
    