version: 2.1

jobs: 
  test:
    docker:
      - image: cimg/base:latest
    steps:
      - checkout
      - run: echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin docker.io
      - run: docker pull stevenkrawczyk/reviewers-like-you
      - run: ./tests/run_tests.sh

workflows:
  run_tests:
    jobs:
      - test
