#!/bin/sh

protected_branch='main'

policy="[Policy] Never push code directly to the "$protected_branch" branch! (Prevented with pre-push hook.)"

current_branch=$(git rev-parse --abbrev-ref HEAD)

do_exit(){
  echo $policy
  exit 1
}

# Rule 1. Do not push to origin/main
if [ $current_branch = $protected_branch ]; then
  do_exit
fi
unset do_exit

# Rule 2. Do not push if end-to-end tests are breaking
pytest tests/test_pipeline_in_memory.py

exit 0

