name: 'Docker Image Create'
on:
  push:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'docker-compose.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin docker.io
          docker image build --no-cache --tag stevenkrawczyk/reviewers-like-you:latest .
          docker push stevenkrawczyk/reviewers-like-you:latest
