name: 'Pull Request Checks'
on: [pull_request]

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin docker.io
          docker pull stevenkrawczyk/reviewers-like-you
      - name: Generate coverage report
        run: |
          ./tests/get_coverage.sh
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: data/metrics/pytest/coverage_report.txt
