name: Testing and Coverage

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        PYTHON_VERSION: 3.9.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Pull DynamoDb docker image
      run: |
        docker pull amazon/dynamodb-local
    - name: Test with pytest
      env:
        AWS_ACCESS_KEY_ID: fakeKeyId
        AWS_SECRET_ACCESS_KEY: fakeAccessKey
        AWS_DEFAULT_REGION: us-west-2
      run: |
        pytest
    - name: Generate coverage report
      env:
        AWS_ACCESS_KEY_ID: fakeKeyId
        AWS_SECRET_ACCESS_KEY: fakeAccessKey
        AWS_DEFAULT_REGION: us-west-2
      run: |
        pytest . --cov > data/cov.txt
    - name: Add coverage comment
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: data/cov.txt
    - name: Check code coverage
      uses: dima-engineer/pytest-cover@v0.1
      with:
        python-version: 3.9
        pytest-root-dir: '.'
        cov-omit-list: 'tests/*, app/ingestion/main_datastore_proxy.py'
        cov-threshold-single: 90
        cov-threshold-total: 95


