name: Testing and Coverage

on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'tools/infra/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Pull docker images
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin docker.io
        docker pull amazon/dynamodb-local
        docker pull minio/minio
        docker pull stevenkrawczyk/reviewers-like-you
    - name: Run tests
      env:
        AWS_ACCESS_KEY_ID: fakeKeyId
        AWS_SECRET_ACCESS_KEY: fakeAccessKey
        AWS_DEFAULT_REGION: us-west-2
      run: |
        ./tests/run_tests.sh
    - name: Check test coverage
      env:
        AWS_ACCESS_KEY_ID: fakeKeyId
        AWS_SECRET_ACCESS_KEY: fakeAccessKey
        AWS_DEFAULT_REGION: us-west-2
      run: |
        ./tests/get_coverage.sh
